[project]
name = "my_crew"
version = "0.1.0"
description = "my_crew using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "chunkr-ai>=0.0.49",
    "crewai[tools]>=0.118.0,<1.0.0",
    "fastapi>=0.115.12",
    "mistralai>=1.7.0",
    "pinecone[grpc]>=6.0.2",
    "playwright>=1.52.0",
    "supabase>=2.15.1",
    "tavily-python>=0.7.2",
    "uvicorn>=0.34.2",
]

[project.scripts]
my_crew = "my_crew.main:run"
run_crew = "my_crew.main:run"
train = "my_crew.main:train"
replay = "my_crew.main:replay"
test = "my_crew.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
